export const PRODUCTS_REQUEST = 'PRODUCTS_REQUEST';
export const PRODUCTS_SUCCESS = 'PRODUCTS_SUCCESS';
export const PRODUCTS_FAILURE = 'PRODUCTS_FAILURE';

export const ADD_FILTER = 'ADD_FILTER';
export const REMOVE_FITLER = 'REMOVE_FITLER';
export const REMOVE_GROUP_FILTERS = 'REMOVE_GROUP_FILTERS';
