export const PRODUCTS_REQUEST = 'PRODUCTS_REQUEST';
export const PRODUCTS_SUCCESS = 'PRODUCTS_SUCCESS';
export const PRODUCTS_FAILURE = 'PRODUCTS_FAILURE';

export const TOGGLE_FILTER = 'TOGGLE_FILTER';
export const REMOVE_GROUP_FILTERS = 'REMOVE_GROUP_FILTERS';
